import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import StoreProvider from "@/app/StoreProvider";
import RightMenu from "@/app/Components/Right-menu/index";
import {NextUIProvider} from '@nextui-org/react'


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create News App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <StoreProvider>
                <RightMenu/>
                {children}
            </StoreProvider>
        </body>
        </html>
    )
}
